### ISSUE TITLE
Unable to use anvil menu on 1.20.4

### ISSUE THREAD

**Issue by typicalsmc** [DevNatan/inventory-framework#754]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 🐛 Describe the bug

`[08:55:47] [Server thread/WARN]: java.lang.NoSuchFieldException: no such field: net.minecraft.server.level.EntityPlayer.playerConnection/net.minecraft.server.network.PlayerConnection/getField
[08:55:47] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:917)
[08:55:47] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
[08:55:47] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3742)`

anvil menu doesnt work

### ✔️ Expected behavior

anvil menu working

### 💻 Platform

- [ ] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Server Version

1.20.4

### 📚 Library Version

3.3.8

### ✍️ Additional context

Log: https://pastes.dev/pyw81gTRjB#L241
Plugin source code: https://github.com/SimpMC-Studio/SimpPay

**Comment by TypicalShavonne** [comment]
its not from my plugin because IF anvilgui is working fine on 1.21.4

Vào Th 3, 10 thg 6, 2025 lúc 20:12 Mondlw ***@***.***> đã
viết:

**Comment by DevNatan** [comment]
Fixed @ https://github.com/DevNatan/inventory-framework/releases/tag/v3.4.0
